#name: "Yedort Blog"
title: "Yedort Blog"

defaults:
  -
    scope:
      path: "index"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      author: "Yedort"
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
